// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5-SwRJIFOjF3xUGKqGfvvQLxhLx3jegQ',
    appId: '1:264716996242:android:350c404babf62b1ea6604b',
    messagingSenderId: '264716996242',
    projectId: 'myfirstflutter-60ecd',
    databaseURL: 'https://myfirstflutter-60ecd-default-rtdb.firebaseio.com',
    storageBucket: 'myfirstflutter-60ecd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_KuES9CsdSoDj7VT1WmPKuifmBAP0Gmk',
    appId: '1:264716996242:ios:9b600f2ad82e383ca6604b',
    messagingSenderId: '264716996242',
    projectId: 'myfirstflutter-60ecd',
    databaseURL: 'https://myfirstflutter-60ecd-default-rtdb.firebaseio.com',
    storageBucket: 'myfirstflutter-60ecd.appspot.com',
    iosClientId: '264716996242-9jruvrvbg8nas31p5bolbru23v5ha18u.apps.googleusercontent.com',
    iosBundleId: 'com.example.onlineLearner',
  );
}
